#alias virtualenv="/opt/python/bin/virtualenv"
alias venv="virtualenv"
alias play="cd /var/www/play"
alias j="jobs"
alias k="kill"
alias k1="kill %1"
alias k2="kill %2"
alias k3="kill %3"
alias k4="kill %4"
alias k5="kill %5"
alias k6="kill %6"
alias k7="kill %7"
alias k8="kill %8"
alias k9="kill %9"
alias k10="kill %10"
alias noc='ssh kovalchuk@noc.drom.ru'
alias grep='LANG=C grep'
alias n10='. ~/.nvm/nvm.sh && nvm use 0.10'
alias n11='. ~/.nvm/nvm.sh && nvm use 0.11'
alias n12='. ~/.nvm/nvm.sh && nvm use 0.12'
